title: StreetFit Calisthenics
description: Free bodyweight workouts & skill progressions.
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
author: You
twitter_username:
github_username: YOURUSERNAME
permalink: /:categories/:title/
